version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: banking-db
    environment:
      - POSTGRES_USER=ghizlane
      - POSTGRES_PASSWORD=ghizlane
      - POSTGRES_DB=banking_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - banking-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ghizlane" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  banking-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    